server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crud_demo_db
    username: postgres
    password: 2!p!vaIL
    pool:
      initial-size: 5
      max-size: 20

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
